# Site settings
title: Nathan Shane
description: >
  Nathan Shane is a Tbilisi-based web developer. He works part-time for
  the data-communication NGO JumpStart Georgia on projects like
  prisoners.watch, and as a freelancer on projects that capture his interest.
# the subpath of your site, e.g. /blog/
baseurl: ""
# the base hostname & protocol for your site
url: 'http://nathanshane.me'
github_username: nwshane

# Build settings
markdown: kramdown
